[build]
  # Only run your actual build script — Netlify already installs dependencies
  command = "CI= npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true" # prevents interactive prompts

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Disable Netlify's slow post-processing since your dist is small
[build.processing]
  skip_processing = true

# Enable caching to speed up builds
[build.cache]
  paths = [
    "node_modules",
    ".netlify/cache"
  ]
