[build]
  # Run only your actual build script — Netlify installs dependencies automatically
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true" # Prevents interactive prompts during build

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Disable Netlify's post-processing to avoid slow image/HTML optimization
[build.processing]
  skip_processing = true

# Enable caching for faster subsequent builds
[build.cache]
  paths = [
    "node_modules",
    "dist/spa"
  ]
